version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: build-stage
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_ORDER_SERVICE_URL=http://order-service:3002
    command: npm run dev
    networks:
      - app-network

  product-service:
    build:
      context: ./services/product-service
    ports:
      - "3000:3000"
    volumes:
      - ./services/product-service:/app
      - /app/node_modules
    secrets:
      - jwt_secret
      - mongodb_uri_products
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongodb
    networks:
      - app-network

  auth-service:
    build:
      context: ./services/auth-service
    expose:
      - "3001"
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    secrets:
      - jwt_secret
      - mongodb_uri_auth
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongodb
    networks:
      - app-network

  order-service:
    build:
      context: ./services/order-service
    expose:
      - "3002"
    volumes:
      - ./services/order-service:/app
      - /app/node_modules
    secrets:
      - jwt_secret
      - mongodb_uri_orders
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    secrets:
      - mongodb_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_root_password
    networks:
      - app-network

  init-products:
    image: curlimages/curl:latest
    volumes:
      - ./scripts:/scripts
    secrets:
      - jwt_secret
    command: ["sh", "/scripts/init-products.sh"]
    depends_on:
      - product-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:

secrets:
  mongodb_root_password:
    file: ./secrets/mongodb_root_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  mongodb_uri_auth:
    file: ./secrets/mongodb_uri_auth.txt
  mongodb_uri_products:
    file: ./secrets/mongodb_uri_products.txt
  mongodb_uri_orders:
    file: ./secrets/mongodb_uri_orders.txt