version: '3.8'

services:
  auth-service:
    image: ${REGISTRY:-localhost}/auth-service:${TAG:-latest}
    build: ./services/auth-service
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    secrets:
      - mongodb_uri_auth
      - jwt_secret
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - backend
    depends_on:
      - mongodb

  product-service:
    image: ${REGISTRY:-localhost}/product-service:${TAG:-latest}
    build: ./services/product-service
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    secrets:
      - mongodb_uri_products
      - jwt_secret
    environment:
      - NODE_ENV=production
      - PORT=3002
    networks:
      - backend
    depends_on:
      - mongodb

  order-service:
    image: ${REGISTRY:-localhost}/order-service:${TAG:-latest}
    build: ./services/order-service
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    secrets:
      - mongodb_uri_orders
      - jwt_secret
    environment:
      - NODE_ENV=production
      - PORT=3003
    networks:
      - backend
    depends_on:
      - mongodb

  frontend:
    image: ${REGISTRY:-localhost}/frontend:${TAG:-latest}
    build: ./frontend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3002
      - VITE_ORDER_SERVICE_URL=http://order-service:3003
    networks:
      - frontend
      - backend
    depends_on:
      - auth-service
      - product-service
      - order-service

  mongodb:
    image: mongo:4.4
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - mongodb_data:/data/db
    secrets:
      - mongodb_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_root_password
    networks:
      - backend

secrets:
  mongodb_root_password:
    file: ./secrets/mongodb_root_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  mongodb_uri_auth:
    file: ./secrets/mongodb_uri_auth.txt
  mongodb_uri_products:
    file: ./secrets/mongodb_uri_products.txt
  mongodb_uri_orders:
    file: ./secrets/mongodb_uri_orders.txt

networks:
  frontend:
  backend:

volumes:
  mongodb_data: